"""add id column and change primary key.

Revision ID: 25034d34b233
Revises: ca1a523101d4
Create Date: 2023-03-04 15:17:21.266650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25034d34b233'
down_revision = 'ca1a523101d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
