"""addtional website field for artist table

Revision ID: 70f6f08a0599
Revises: f366a3c85305
Create Date: 2023-03-05 19:51:02.262832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f6f08a0599'
down_revision = 'f366a3c85305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('seeking_description')

    # ### end Alembic commands ###
