"""start time column.

Revision ID: ca1a523101d4
Revises: f5699ac00ec2
Create Date: 2023-03-04 14:47:21.724095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1a523101d4'
down_revision = 'f5699ac00ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
